TWELVE_DATA_KEY = "d780efe2ed9f405da6aaec55d3c13232"
NEWS_API_KEY = "52226a2a8321453ab0ae2afb65fc5670"
TELEGRAM_BOT_TOKEN = "8040861426:AAHso8x2F7MiJZpnuKNB3EeR0dTjozy_c4Q"
TELEGRAM_CHAT_ID = "5952109301"
EMAIL_USER = "kadegbie@gmail.com"
EMAIL_PASS = "pivn afak yekw spug"
ALERT_EMAIL_RECEIVER = "seedtimecapital@gmail.com"


